"""Crear tablas iniciales

Revision ID: 66e894caf82c
Revises: 
Create Date: 2026-08-27 17:29:20.240192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e894caf82c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('anio_carrera', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'ALUMNO', name='rolenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('historial_academico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_academico_id'), 'historial_academico', ['id'], unique=False)
    op.create_table('materia_correlativa',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('correlativa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correlativa_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id', 'correlativa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materia_correlativa')
    op.drop_index(op.f('ix_historial_academico_id'), table_name='historial_academico')
    op.drop_table('historial_academico')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    # ### end Alembic commands ###
